InfosystemOrchestrator/InfosystemOrchestrator/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path

import screen.views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('screen/<str:passphrase>/', screen.views.screen_view),
    path('generate/<str:name>/', screen.views.generate_screen),
    path('switch_group/<str:access_token>/<int:group>/<int:new_command>', screen.views.switch_command_group),
    path('switch_screen/<str:access_token>/<int:screen_id>/<int:new_command>', screen.views.switch_command_screen),
    path('switch_screen_override/<str:access_token>/<int:screen_id>/', screen.views.switch_screen_override),
    path('screen_info/<str:access_token>/<int:screen_id>/', screen.views.screen_info),
    path('screen_group_info/<str:access_token>/<int:screen_group_id>/', screen.views.screen_group_info),
    path('metrics/', screen.views.metrics)
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

InfosystemOrchestrator/printingserver/models.py
from django.contrib.auth.models import User
from django.db import models


# Create your models here.
class StoredDocument(models.Model):
    DocumentPriorityChoice = [
        (1, "No Rush"),
        (2, "Need this tomorrow"),
        (3, "Need this in a few hours"),
        (4, "Need this in hour"),
        (5, "ASAP")
    ]
    created = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    priority = models.IntegerField(choices=DocumentPriorityChoice)
    description = models.CharField(max_length=255)
    delivery_location = models.CharField(max_length=255)
    number_of_pages = models.IntegerField()

    printed_at = models.DateTimeField(null=True, blank=True)

    file_to_print = models.FileField()

    @property
    def is_printed(self):
        return bool(self.printed_at is not None)

    def __str__(self):
        return f"Document: {self.description} from {self.user.username}"

InfosystemOrchestrator/printingserver/forms.py
from django import forms

from printingserver.models import StoredDocument


class UploadForm(forms.ModelForm):
    description = forms.CharField(label="Document description", max_length=100)
    file_to_print = forms.FileField(label="File to upload. Please do PDF")

    class Meta:
        model = StoredDocument
        fields = ['description', 'file_to_print', 'number_of_pages', 'priority', 'delivery_location']

InfosystemOrchestrator/printingserver/views.py
from asgiref.sync import async_to_sync
from channels.layers import get_channel_layer
from django.conf import settings
from django.shortcuts import render, redirect
from rest_framework.decorators import api_view
from rest_framework.response import Response

from printingserver.consumers import PrintingServiceWebsocket
from printingserver.forms import UploadForm


# Create your views here.
@api_view(["GET", "POST"])
def upload_form(request):
    if request.method == 'GET':
        if not request.user.is_authenticated:
            return redirect("/admin/login/?next=/upload_form/")
        else:
            return render(request, "upload_form.html", context={
                'user': request.user.username,
                'form': UploadForm()
            })
    elif request.method == 'POST':
        form = UploadForm(request.POST, request.FILES)
        form.instance.user_id = request.user.id

        if not form.is_valid():
            return render(request, "upload_form.html", context={"error_message": form.errors})
        else:
            form.save()
            return render(request, "upload_form.html", context={"success_message": "Success!"})


def notification_receiver(request):
    if not request.user.is_authenticated:
        return redirect("/admin/login/?next=/notification_receiver/")
    else:
        return render(request, "notification_receiver.html")


@api_view(['GET'])
def test_call(request):
    async_to_sync(get_channel_layer().group_send)(settings.PRINTING_SERVICE_GROUP,
                                                  {"type": "system.message", "message": "Bajo jajo"})
    return Response(status=200, data={"yes": "no"})

InfosystemOrchestrator/printingserver/templates/notification_receiver.html
<!-- chat/templates/chat/room.html -->
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>Chat Room</title>
</head>
<body>
    <div>
        <p>Documents in queue</p>
        <p id="queue">0</p>

    </div>
    <textarea id="chat-log" cols="100" rows="20"></textarea><br>

    <input id="chat-message-input" type="text" size="100"><br>
    <input id="chat-message-submit" type="button" value="Send">
    <script>

        const chatSocket = new WebSocket(
            'ws://'
            + window.location.host
            + '/ws/printingservice/'
        );
        chatSocket.onopen = function (e){
            chatSocket.send(JSON.stringify({
                "type": "data"
            }));
        };

        chatSocket.onmessage = function(e) {
            const data = JSON.parse(e.data);
            console.log(data);
            if(data.type === "data"){
                document.getElementById("queue").innerText = data['queue'];
            }
        };

        chatSocket.onclose = function(e) {
            console.error('Chat socket closed unexpectedly');
        };


        document.querySelector('#chat-message-submit').onclick = function(e) {
            const messageInputDom = document.querySelector('#chat-message-input');
            const message = messageInputDom.value;
            chatSocket.send(JSON.stringify({
                'message': message
            }));
            messageInputDom.value = '';
        };
    </script>
</body>
</html>

InfosystemOrchestrator/printingserver/templates/upload_form.html
<html>
<body>
<!--{{user}} będzie podmieniony na nickname usera-->
<p>Welcome {{user}}</p>
<!--ACTION zostawić taki jak tutaj, to będzie automatycznie resolwowane do odpowiedniego stringa-->
<form enctype="multipart/form-data" action="{% url 'upload_form' %}" method="post">
<!--    To gdziekolwiek żeby było -->
{% csrf_token %}
    <fieldset>
<!--        Tutaj jest sekcja błąd i error - automatycznie będzie to ogarnięte przez django template language. Podmień styl traktując te successmessage i error message jako string -->
        {% if success_message %}<p><strong>{{ success_message }}</strong></p>{% endif %}
        {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<!--        To usunąć i tutaj zrobić Formularz-->


         <label for="id_description">Document description:</label>
         <input type="text" name="description" maxlength="100" required="" id="id_description" value="">

         <label for="id_file_to_print">File to upload. Please do PDF:</label>
         <input type="file" name="file_to_print" required="" id="id_file_to_print" value="">

         <label for="id_number_of_pages">Number of pages:</label>
         <input type="number" name="number_of_pages" required="" id="id_number_of_pages" value="">

         <label for="id_priority">Priority:</label>
         <select name="priority" required="" id="id_priority">

             <option value="" selected="">---------</option>
             <option value="1">No Rush</option>
             <option value="2">Need this tomorrow</option>
             <option value="3">Need this in a few hours</option>
             <option value="4">Need this in hour</option>
             <option value="5">ASAP</option>
        </select>

 <label for="id_delivery_location">Delivery location:</label>
 <input type="text" name="delivery_location" maxlength="255" required="" id="id_delivery_location" value="">

</fieldset>
<input type="submit" value="Submit">
</form>

</body>
</html>